paths:
  data_dir: "../data/mcmc_termalization_data"
  plot_dir: "../plots/mcmc_termalization_plots"
  log_dir: "../logs/mcmc_termalization_logs/"
  docs_dir: "../docs/mcmc_termalization_docs/"
  tests_dir: "../tests"

settings:
  max_lag_default: 1000
  file_extension: ".bin"
  x_scale: "log"  # Options: linear, log
  y_scale: "linear"     # Options: linear, log
  plot_title_format: "Lattice Side: {lattice_side}, Beta: {beta}"  # Plot title format