settings:
  max_block_size_default: 1000
  num_cores_default: 4
  data_columns: ["L", "beta", "mx", "my", "epsilon", "absm", "m2", "m4"]

paths:
  log_dir: "../logs"
  data_dir: "../data/blocking_data"
  plot_dir: "../plots/blocking_plots"
  default_files: 
    - "../data/lattice_metrics_csv/L15/data_L15_b0.408_summary.csv"