settings:
  max_block_size_default: 1000
  num_cores_default: 4
  data_columns: ["L", "beta", "mx", "my", "epsilon", "absm", "m2", "m4"]

paths:
  log_dir: "../logs"
  data_dir: "../data/blocking_data"
  plot_dir: "../plots/blocking_plots"
  default_files: 
    - "../data/blocking_data/L9/data_L9_b0.453_summary_blocking_10000.csv"
    - "../data/blocking_data/L18/data_L18_b0.453_summary_blocking_10000.csv"
    - "../data/blocking_data/L30/data_L30_b0.453_summary_blocking_10000.csv"
    
    