paths:
  file_name_means: "../data/secondary_quantities/secondary_quantities_means.csv"
  file_name_vars: "../data/secondary_quantities/secondary_quantities_variances.csv"
  plot_dir: "../plots/fss_plots"
  file_name_fit_results: "fss_fit_results.csv"
  absm: "../data/principal_quantities/principal_quantities_means.csv"

settings:
  variables_to_plot: ["U", "chi_prime", "C"]
  variables_names_latex: ["U", "$\\chi$'", "C"]
  beta_min_max: [[0.4325, 0.459], [0.441, 0.4566], [0.446, 0.4554], [0.447, 0.4554], [0.0, 1.0], [0.0, 1.0], [0.0, 1.0], [0.0, 1.0]]
  scaled_variables_to_plot: ["U", "chi_prime", "C"]
  scaled_variables_names_latex: ["U", "$\\chi' / L^{\\gamma/\\nu}$", "$ C / L^{\\alpha / \\nu}$"] #, "$<{|\\mathbf{m}|}>L^{\\beta/\\nu}$"]

critical_values:
  nu: 0.66184
  gamma: 1.315
  beta_c: 0.45426
