settings:
  first_index: 5000
  max_block_size_default: 1000
  num_cores_default: 4
  data_columns: ["L", "beta", "absm", "m2", "m4"]

paths:
  log_dir: "../logs"
  output_dir: "../data/jackknife_data"
  plot_dir: "../plots/jackknife_plots"
  default_files: 
    - "../data/lattice_metrics_csv/L9/data_L9_b0.453_summary.csv"
    - "../data/lattice_metrics_csv/L30/data_L30_b0.453_summary.csv"
    
    
