paths:
  data_dir: "../data/mcmc_termalization_data"
  plot_dir: "../plots/mcmc_termalization_plots"
  log_dir: "../logs/mcmc_termalization_logs/"
  docs_dir: "../docs/mcmc_termalization_docs/"
  tests_dir: "../tests"
  default_files:
    - "../data/raw_data/data/lattice30/data_b.45253_L30.bin"             
    - "../data/raw_data/data/lattice30/data_b.45406_L30.bin"        
    - "../data/raw_data/data/lattice18/data_b.45426_L18.bin" 
    - "../data/raw_data/data/lattice18/data_b.45954_L18.bin"     
    
settings:
  max_lag_default: 100
  file_extension: ".bin"
  x_scale: "linear"  # Options: linear, log
  y_scale: "log"     # Options: linear, log
  plot_title_format: "Lattice Side: {lattice_side}, Beta: {beta}"  # Plot title format
  
  
