paths:
  data_dir: "../data/mcmc_termalization_data"
  plot_dir: "../plots/mcmc_termalization_plots"
  log_dir: "../logs/mcmc_termalization_logs/"
  docs_dir: "../docs/mcmc_termalization_docs/"
  tests_dir: "../tests"
  default_files:
    - "../data/simulation_data/simulations_9_30/data/lattice30/data_b0.45336_L30.bin"         # lower-critical beta (T slightly upper thant Tc)
    - "../data/simulation_data/simulations_9_30/data/lattice30/data_b0.45504_L30.bin"         # upper-critical beta (T slightly lower thant Tc)
    - "../data/simulation_data/simulations_9_30/data/lattice30/data_b0.46680_L30.bin"         # highest beta (lower T)
    - "../data/simulation_data/simulations_9_30/data/lattice18/data_b0.45336_L18.bin"    
    - "../data/simulation_data/simulations_9_30/data/lattice18/data_b0.45504_L18.bin"    
    - "../data/simulation_data/simulations_9_30/data/lattice18/data_b0.46680_L18.bin"    
    - "../data/simulation_data/simulations_9_30/data/lattice9/data_b0.45336_L9.bin"
    - "../data/simulation_data/simulations_9_30/data/lattice9/data_b0.45504_L9.bin"
    - "../data/simulation_data/simulations_9_30/data/lattice9/data_b0.46680_L9.bin"  

settings:
  max_lag_default: 1000
  file_extension: ".bin"
  x_scale: "linear"  # Options: linear, log
  y_scale: "log"     # Options: linear, log
  plot_title_format: "Lattice Side: {lattice_side}, Beta: {beta}"  # Plot title format